Script started on 2020-10-11 05:37:53-06:00
]0;keaton.banik1@csa1:~/Desktop/355/A2keaton.banik1@csa1:~/Desktop/355/A2$ gdb assign2a[17@cc assign2a.s -g -o[C[C[C[C[C[C[C[C[C[13Pemacs assign2a.scd A2[K355Desktop[1PDesktop Desktop[4P355[1PA2emacs assign2a.sgcc assign2a.s -g -o assign2a[17Pdb[C[C[C[C[C[C[C[C[C[17@cc assign2a.s -g -o[C[C[C[C[C[C[C[C[C
]0;keaton.banik1@csa1:~/Desktop/355/A2keaton.banik1@csa1:~/Desktop/355/A2$ gcc assign2a.s -g -o assign2a[17Pdb[C[C[C[C[C[C[C[C[C
GNU gdb (GDB) Fedora 8.1.1-4.fc28
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from assign2a...done.
(gdb) l
1		//Author: Keaton Banik
2		//Description: Assembly Code without macros for Assignment 2.
3		//Prints out a User Inputed Number of Random numbers between 0-9 and calculates and prints the frequency and sum/size of the numbers generated
4	
5	
6	//String Formats
7	fmt:		.string "Enter a number between 5-20: " 			// Format String for Initial Prompt
8	input0:		.string "%d" 							// Format String for scanf input
9	word:		.string "\n The input numbers are: \n" 				// Format String for output displaying 
10	rannum:		.string "%d " 							// Format String for to output random generated numbers
(gdb) r
Starting program: /home/uga/keaton.banik1/Desktop/355/A2/assign2a 
warning: the debug information found in "/usr/lib/debug//usr/lib64/ld-2.27.so.debug" does not match "/lib/ld-linux-aarch64.so.1" (CRC mismatch).

Missing separate debuginfos, use: dnf debuginfo-install glibc-2.27-38.fc28.aarch64
warning: the debug information found in "/usr/lib/debug//lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

Enter a number between 5-20: 4
User Input is too low, Please Try again 
[Inferior 1 (process 2076) exited with code 051]
(gdb) r
Starting program: /home/uga/keaton.banik1/Desktop/355/A2/assign2a 
warning: the debug information found in "/usr/lib/debug//usr/lib64/ld-2.27.so.debug" does not match "/lib/ld-linux-aarch64.so.1" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

Enter a number between 5-20: 21
User Input is too high, Please Try again 
[Inferior 1 (process 2091) exited with code 052]
(gdb) r
Starting program: /home/uga/keaton.banik1/Desktop/355/A2/assign2a 
warning: the debug information found in "/usr/lib/debug//usr/lib64/ld-2.27.so.debug" does not match "/lib/ld-linux-aarch64.so.1" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

Enter a number between 5-20: 15

 The input numbers are: 
8 1 3 0 3 4 9 5 6 0 7 4 7 0 1 The size of the document is: 58 
The Lowest frequency in the document is: 0 % 
The Highest frequency in the document is: 15 % 
[Inferior 1 (process 2094) exited with code 060]
(gdb) r
Starting program: /home/uga/keaton.banik1/Desktop/355/A2/assign2a 
warning: the debug information found in "/usr/lib/debug//usr/lib64/ld-2.27.so.debug" does not match "/lib/ld-linux-aarch64.so.1" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

Enter a number between 5-20: 10

 The input numbers are: 
0 3 3 9 1 7 1 8 7 3 The size of the document is: 42 
The Lowest frequency in the document is: 0 % 
The Highest frequency in the document is: 21 % 
[Inferior 1 (process 2104) exited with code 060]
(gdb) r[Kr
Starting program: /home/uga/keaton.banik1/Desktop/355/A2/assign2a 
warning: the debug information found in "/usr/lib/debug//usr/lib64/ld-2.27.so.debug" does not match "/lib/ld-linux-aarch64.so.1" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

Enter a number between 5-20: 5

 The input numbers are: 
2 9 7 6 5 The size of the document is: 29 
The Lowest frequency in the document is: 6 % 
The Highest frequency in the document is: 31 % 
[Inferior 1 (process 2123) exited with code 060]
(gdb) r
Starting program: /home/uga/keaton.banik1/Desktop/355/A2/assign2a 
warning: the debug information found in "/usr/lib/debug//usr/lib64/ld-2.27.so.debug" does not match "/lib/ld-linux-aarch64.so.1" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

Enter a number between 5-20: 20

 The input numbers are: 
3 0 2 1 3 9 7 1 9 2 3 1 5 7 1 9 8 9 8 1 The size of the document is: 89 
The Lowest frequency in the document is: 0 % 
The Highest frequency in the document is: 10 % 
[Inferior 1 (process 2136) exited with code 060]
(gdb) q
]0;keaton.banik1@csa1:~/Desktop/355/A2keaton.banik1@csa1:~/Desktop/355/A2$ exit
exit

Script done on 2020-10-11 05:38:51-06:00
